### ISSUE TITLE
谈谈一些有趣的CSS题目（1~5）

### ISSUE THREAD

**Issue by voidove** [voidove/css#1]
## 1. 下面这个图形，只使用一个标签，可以有多少种实现方式：

![1](https://user-images.githubusercontent.com/5563419/34605729-9b0f562c-f247-11e7-9830-664955e48fcf.png)
假设我们的单标签是一个 div:
```html
<div></div>
```
定义如下通用`CSS`：
```css
div {
  width: 100px;
  height: 50px;
  background: #ddd;
}
```
方法一：border
```css
div {
  border-left: 6px solid deeppink;
}
```
方法二：伪元素
```css
div {
  content: "";
  width: 6px;
  display: block;
  height: 100%;
  background: deeppink;
}
```
方法三：box-shadow

Reference:
[chokcoco/iCSS](https://github.com/chokcoco/iCSS/issues/1)
https://codepen.io/yumu128/pen/wprEVo
